CREATE SCHEMA IF NOT EXISTS contacts_schema;

CREATE TABLE IF NOT EXISTS contacts_schema.contacts
(
id BIGINT PRIMARY KEY,
firstName VARCHAR(256) NOT NULL,
lastName VARCHAR(256) NOT NULL,
email VARCHAR(256) NOT NULL,
phone VARCHAR(256) NOT NULL
);